# Generated by Django 3.2.4 on 2021-06-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('startdate', models.DateField(blank=True)),
                ('enddate', models.DateField(blank=True)),
            ],
        ),
    ]
